spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: postgres
    password: root
  datasource:
    url: "jdbc:postgresql://localhost:1488/shem"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none

server:
  address: "127.0.0.1"
  port: 777

logging:
  level:
    root:
    WARN org.springframework.boot: DEBUG
    org.example: DEBUG

features:
  sent-email:
    enabled: false
  format-phone:
    enabled: true
