spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: root
    password: root
  datasource:
    url: "jdbc:mysql://localhost:1488/shem"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none

server:
  address: "127.0.0.1"
  port: 7777

logging:
  level:
    root:
    WARN org.springframework.boot: DEBUG
    org.example: DEBUG

features:
sent-email:
  enabled: false
format-phone:
  enabled: true
