version: "3"
services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shem
      POSTGRES_PORT: 5432
    ports:
      - "1488:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data:
